auto: true
pygments: true
server: true
markdown: rdiscount
permalink: /:categories/:title/
email: info@teachosm.org
columnist:
  paths:
  - _posts
baseurl: ''
rdiscount:
  extensions: [smart]
prose:
  rooturl: '_posts'
translations:
  en:
    tagline: "Teach OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!" 
